apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: don-ju-songs
  namespace: don-ju
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
